version: '3.8'

services:
  app:
    image: node:latest
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      - DB_USER=postgres
      - DB_HOST=localhost
      - DB_NAME=movies_db
      - DB_PASSWORD=Narek100*
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Narek100*
      POSTGRES_DB: movies_db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data